lein, project.clj, test/kouta_indeksoija_service/queue/queue_test.clj
Testasin, että tämä toimii nyt sekä Javan versioilla 8 että 11.
=> Java 11 yhteensopivuus

project.clj, src/kouta_indeksoija_service/indexer/kouta/koulutus_search.clj, test/resources/kouta/kouta-koulutus-result.json, test/resources/kouta/kouta-oppilaitos-result.json, test/resources/kouta/kouta-toteutus-result.json, test/resources/search/koulutus-search-item-no-toteutukset.json, test/resources/search/koulutus-search-item-toteutukset.json
Testien korjaus.
Pää-PR: https://github.com/Opetushallitus/kouta-backend/pull/63
=> KTO-557 Teemakuvat siirretty päätasolle metadatasta

.travis.yml, README.md, README_INDEKSOINTI.md, project.clj, src/kouta_indeksoija_service/api.clj, src/kouta_indeksoija_service/elastic/admin.clj, src/kouta_indeksoija_service/elastic/settings.clj, src/kouta_indeksoija_service/elastic/tools.clj, src/kouta_indeksoija_service/indexer/indexable.clj, src/kouta_indeksoija_service/indexer/indexer.clj, src/kouta_indeksoija_service/queuer/last_queued.clj, src/kouta_indeksoija_service/util/time.clj, test/kouta_indeksoija_service/elastic/admin_test.clj, test/kouta_indeksoija_service/elastic/rebuild_test.clj, test/kouta_indeksoija_service/elastic/tools_test.clj, test/kouta_indeksoija_service/fixture/common_indexer_fixture.clj, test/kouta_indeksoija_service/fixture/kouta_indexer_fixture.clj, test/kouta_indeksoija_service/indexer/eperuste_indexer_test.clj, test/kouta_indeksoija_service/indexer/koodisto_indexer_test.clj, test/kouta_indeksoija_service/indexer/kouta_search_index_test.clj, test/kouta_indeksoija_service/notifier/notification_test.clj, test/kouta_indeksoija_service/queuer/last_queued_test.clj, test/kouta_indeksoija_service/test_tools.clj, test/misc/analyze_settings_test_tool.clj
Readmessa on kuvaus toiminnasta
=> KTO-627 katkottomat indeksoinnit

project.clj, src/kouta_indeksoija_service/indexer/kouta/toteutus.clj, test/kouta_indeksoija_service/fixture/external_services.clj, test/kouta_indeksoija_service/fixture/kouta_indexer_fixture.clj, test/resources/kouta/kouta-haku-result.json, test/resources/kouta/kouta-hakukohde-result.json, test/resources/kouta/kouta-toteutus-result.json
Lisätty järjestyspaikan rikastus toteutukselle.
=> Kto 920 jarjestyspaikka

project.clj, test/kouta_indeksoija_service/indexer/kouta_koulutus_test.clj
Korvattu embedded elasticin käyttö konttielasticilla
=> Embedded elastic replace

src/kouta_indeksoija_service/indexer/kouta/koulutus.clj, test/kouta_indeksoija_service/fixture/kouta_indexer_fixture.clj, test/kouta_indeksoija_service/indexer/kouta_koulutus_test.clj
Useampaan tutkinnon-osaan voi liittyä sama koulutusala. Indeksoidaan ainoastaan uniikit koulutusalat. Lisätty testeihin tutkinnon-osa jolla sama koulutuskoodiUri.
=> KTO-1052 duplicate fix

project.clj, test/resources/kouta/kouta-haku-result.json, test/resources/kouta/kouta-valintaperuste-result.json
- nostetttu indeksoijan ja kouta-backendin versioita
- ajastettuJulkaisu testidataan
=> Ajastettu julkaisu testidataan

project.clj, test/resources/kouta/kouta-hakukohde-result.json, test/resources/kouta/kouta-oppilaitos-result.json, test/resources/kouta/kouta-toteutus-result.json, test/resources/kouta/kouta-valintaperuste-result.json
- Nostettu indeksoijan ja kouta-backendin versiota
- Esikatselu-kenttää testidataan
=> Esikatselu testidataan

project.clj, test/resources/kouta/kouta-hakukohde-result.json, test/resources/kouta/kouta-toteutus-result.json, test/resources/kouta/toteutus-metadata.json
- Nostettu kouta-backendin versiota
- Poistettu vanhoja koulutuksen alkamiskauden kenttiä testidatasta
=> Kto 1082 testidatan poistoja

src/kouta_indeksoija_service/api.clj, src/kouta_indeksoija_service/indexer/eperuste/eperuste.clj, src/kouta_indeksoija_service/indexer/eperuste/osaamisalakuvaus.clj, src/kouta_indeksoija_service/indexer/eperuste/tutkinnonosa.clj, src/kouta_indeksoija_service/indexer/indexable.clj, src/kouta_indeksoija_service/indexer/koodisto/koodisto.clj, src/kouta_indeksoija_service/indexer/kouta/common.clj, src/kouta_indeksoija_service/indexer/kouta/haku.clj, src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, src/kouta_indeksoija_service/indexer/kouta/koulutus.clj, src/kouta_indeksoija_service/indexer/kouta/koulutus_search.clj, src/kouta_indeksoija_service/indexer/kouta/oppilaitos.clj, src/kouta_indeksoija_service/indexer/kouta/oppilaitos_search.clj, src/kouta_indeksoija_service/indexer/kouta/sorakuvaus.clj, src/kouta_indeksoija_service/indexer/kouta/toteutus.clj, src/kouta_indeksoija_service/indexer/kouta/valintaperuste.clj, src/kouta_indeksoija_service/indexer/lokalisointi/lokalisointi.clj, src/kouta_indeksoija_service/queue/conf.clj, src/kouta_indeksoija_service/rest/cas/session.clj, src/kouta_indeksoija_service/rest/cas/session_id.clj, src/kouta_indeksoija_service/rest/eperuste.clj, src/kouta_indeksoija_service/rest/lokalisointi.clj, src/kouta_indeksoija_service/rest/util.clj, test/kouta_indeksoija_service/indexer/eperuste_indexer_test.clj, test/kouta_indeksoija_service/indexer/koodisto_indexer_test.clj, test/kouta_indeksoija_service/indexer/kouta_indexer_test.clj, test/kouta_indeksoija_service/indexer/kouta_koulutus_test.clj, test/kouta_indeksoija_service/indexer/lokalisointi_indexer_test.clj
Selvitetty clojure.coren konfliktit kouta-indeksoijan funktioiden kanssa
=> Get rename

src/kouta_indeksoija_service/indexer/kouta/oppilaitos.clj
Käytetään samaa logiikkaa mikä on oppilaitos_search.clj
=> KTO-1160 fix koulutusohjelmia lkm

src/kouta_indeksoija_service/indexer/tools/search.clj, test/kouta_indeksoija_service/indexer/search_tests/kouta_koulutus_search_integration_test.clj
Sallittu tapaus jossa koulutukselle on syötetty useampi kandi, maisteri tai tohtori koulutuskoodi
=> Kto 1133 parannus

project.clj, src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, test/kouta_indeksoija_service/indexer/kouta_indexer_test.clj, test/resources/kouta/kouta-hakukohde-result.json
https://jira.eduuni.fi/browse/HLE-1333
Hakukohderyhmäpalvelussa tarvitaan Sora -mallin "tila"-tietoa hakukohteiden suodattamistarpeisiin.
=> HLE-1333 - Liitä tarvittavat sora-tiedot hakukohteeseen

project.clj, src/kouta_indeksoija_service/indexer/cache/eperuste.clj, src/kouta_indeksoija_service/indexer/kouta/toteutus.clj, test/kouta_indeksoija_service/fixture/external_services.clj, test/kouta_indeksoija_service/fixture/kouta_indexer_fixture.clj, test/kouta_indeksoija_service/indexer/kouta_toteutus_test.clj, test/kouta_indeksoija_service/queue/queue_methods_test.clj, test/kouta_indeksoija_service/queue/sqs_queue_test.clj, test/kouta_indeksoija_service/test_tools.clj, test/resources/kouta/kouta-toteutus-lukio-result.json
- Rikastetaan lukio-toteutuksiin diplomeille sisällöt ja tavoitteet eperusteista.
- Parannettu testien virhe-diffejä luettavammaksi
=> KTO-472: Lukiodiplomit rikastus

src/kouta_indeksoija_service/indexer/koodisto/koodisto.clj, src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, src/kouta_indeksoija_service/indexer/tools/koodisto.clj, test/kouta_indeksoija_service/fixture/external_services.clj, test/kouta_indeksoija_service/fixture/kouta_indexer_fixture.clj, test/kouta_indeksoija_service/indexer/kouta_hakukohde_test.clj, test/kouta_indeksoija_service/indexer/tools/koodisto_tools_test.clj, test/resources/kouta/kouta-hakukohde-result.json, test/resources/kouta/kouta-toteutus-lukio-result.json
https://jira.eduuni.fi/browse/HLE-1408
=> Change koulutustyypit to koulutustyyppikoodi

src/kouta_indeksoija_service/indexer/indexable.clj, src/kouta_indeksoija_service/indexer/indexer.clj, src/kouta_indeksoija_service/queue/state.clj
=> OY-3202 : Fix id logging.

src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, test/kouta_indeksoija_service/indexer/kouta_hakukohde_test.clj, test/resources/kouta/kouta-hakukohde-result.json
https://jira.eduuni.fi/browse/HLE-1616
=> Add new harkinnanvaraisuus flags

src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, src/kouta_indeksoija_service/indexer/tools/koodisto.clj, test/kouta_indeksoija_service/indexer/kouta_hakukohde_test.clj, test/resources/kouta/kouta-hakukohde-result.json
https://jira.eduuni.fi/browse/HLE-1618
=> Hle 1618 remove harkinnanvaraisuus flag

src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, src/kouta_indeksoija_service/indexer/kouta/koulutus.clj, src/kouta_indeksoija_service/indexer/kouta/toteutus.clj, src/kouta_indeksoija_service/indexer/tools/general.clj, src/kouta_indeksoija_service/indexer/tools/koulutustyyppi.clj, src/kouta_indeksoija_service/indexer/tools/search.clj, test/kouta_indeksoija_service/indexer/search_tests/kouta_koulutus_search_test.clj, test/resources/kouta/kouta-hakukohde-result-kielivalinta-fi.json, test/resources/kouta/kouta-hakukohde-result-only-fi.json, test/resources/kouta/kouta-hakukohde-result.json, test/resources/kouta/kouta-koulutus-result.json, test/resources/kouta/kouta-toteutus-lukio-result.json, test/resources/kouta/kouta-toteutus-result.json
Lisätty tarjonta-pulssia varten koulutukselle, toteutukselle ja hakukohteelle kenttä koulutustyyppiPath.
=> OPHJOD-52: Tarjonta-pulssi

src/kouta_indeksoija_service/indexer/kouta/hakukohde.clj, test/resources/kouta/kouta-hakukohde-result.json
Etusivun ja toteutuksen hakukohdelistauksiin haku-sarake ja vapaasanahaku.
=> OY-3663 & OY-3857

README.md, test/mocks/kouta_external_mocks.clj
Lisätty kouta-externalin mock-datadumppiin haku-apille muutama haku lisää vastaavasti kuin kouta-internalissa.
=> OY-4040 lisää hakuja kouta-externalin mockdatadumppiin

src/kouta_indeksoija_service/api.clj
https://jira.eduuni.fi/browse/OY-4000
=> Add kielivalikoima koodisto

resources/kouta-indeksoija-oph.properties, src/kouta_indeksoija_service/indexer/kouta/koulutus.clj, src/kouta_indeksoija_service/indexer/tools/koodisto.clj, src/kouta_indeksoija_service/indexer/tools/search.clj, src/kouta_indeksoija_service/rest/koodisto.clj, test/kouta_indeksoija_service/fixture/external_services.clj, test/kouta_indeksoija_service/fixture/kouta_indexer_fixture.clj, test/kouta_indeksoija_service/indexer/search_tests/kouta_koulutus_search_integration_test.clj, test/kouta_indeksoija_service/indexer/search_tests/kouta_koulutus_search_test.clj, test/kouta_indeksoija_service/indexer/search_tests/kouta_oppilaitos_search_integration_test.clj, test/kouta_indeksoija_service/indexer/tools/koodisto_tools_test.clj, test/kouta_indeksoija_service/indexer/tools/search_test.clj, test/kouta_indeksoija_service/util/conf_test.clj
https://jira.eduuni.fi/browse/OY-4270
Pieni muutos myös konfo-ui:n https://github.com/Opetushallitus/konfo-ui/pull/431
=> OY-4270 include ylakoodit for koulutusalat

src/kouta_indeksoija_service/indexer/kouta/common.clj, test/kouta_indeksoija_service/indexer/kouta_hakukohde_test.clj, test/resources/kouta/kouta-haku-result.json, test/resources/kouta/kouta-hakukohde-result.json, test/resources/kouta/kouta-toteutus-lukio-result.json, test/resources/kouta/kouta-toteutus-result.json, test/resources/kouta/kouta-toteutus-tpo-result.json
Indeksoidaan järjestyspaikan nimet lähimpään parent oppilaitokseen asti
=> OY-4687 Hakukohteen tiedoissa ei näy organisaation nimeä pistelaskurin hakukohdevalikossa

src/kouta_indeksoija_service/rest/cas/session.clj, src/kouta_indeksoija_service/rest/cas/session_id.clj
This reverts commit 91c488ba6d75d3cc0ecdeb01457b376f82cc77fd.
=> Revert "OY-5050 follow redirects true"
